#!/bin/sh
set -e

# Get the commit message
export COM_MSG=`git log -n 1 HEAD --format=format:%s%n%b`

# Exit if commit is not a release
[[ "$COM_MSG" != "Prepare v"* ]] && exit 0

# Get commit message to extract file names
export FILES=`git log --name-only -n 1`

# Loop all commit message lines
for FILE in $FILES; do
  # Skip line if it does not contain .docx file information
  [[ "$FILE" != *".docx" ]] && continue

  # Skip if line is not an existing file
  [[ -f "$FILE" ]] || continue

  # Generate target file name
  export BASE_FOLDER=$(dirname "$FILE")
  export FILE_NAME=$(basename "${FILE/.docx/}")
  export VERSION_NUMBER=${COM_MSG/Prepare v/}
  export VERSION_NUMBER=${VERSION_NUMBER%"."}
  export TARGET="${BASE_FOLDER}/releases/${FILE_NAME}_v${VERSION_NUMBER}.docx"

  echo -e "$FILE" >> C://test.txt
  echo -e "$TARGET" >> C://test.txt

  # Copy file to releases folder
  cp "$FILE" "$TARGET"

  # Check if release file was created
  if test -f "${TARGET}"; then
    # Stage release file for commit
    git add "$TARGET"

    # Commit release to repo
    git commit -m "Release \"${FILE_NAME} v${VERSION_NUMBER}\""
  fi
done

echo "No errors found."

exit 1
